=== cyanite-ai/aws-marketplace/lyrics_analyzer/schemes/marketplace_v1/schema/marketplace_v1.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "extractedLyrics": {
      "type": "string"
    },
    "extractedLyrics_en": {
      "type": "string"
    },
    "detectedLanguage": {
      "type": "string"
    },
    "explicitness": {
      "type": "object",
      "properties": {
        "toxicity": {
          "type": "number"
        },
        "severe_toxicity": {
          "type": "number"
        },
        "obscene": {
          "type": "number"
        },
        "threat": {
          "type": "number"
        },
        "insult": {
          "type": "number"
        },
        "identity_attack": {
          "type": "number"
        }
      },
      "required": [
        "toxicity",
        "severe_toxicity",
        "obscene",
        "threat",
        "insult",
        "identity_attack"
      ]
    }
  },
  "required": [
    "extractedLyrics",
    "extractedLyrics_en",
    "detectedLanguage",
    "explicitness"
  ]
}

=== cyanite-ai/aws-marketplace/lyrics_analyzer/schemes/marketplace_v1/example/marketplace_v1_example_output.json
{"extractedLyrics": "When the dawn starts to creep Back into the sky and it's time to leave We can still feel the drone And it's pulling us right back to where we've begun", "extractedLyrics_en": "When the dawn starts to creep Back into the sky and it's time to leave We can still feel the drone And it's pulling us right back to where we've begun", "detectedLanguage": "en", "explicitness": {"toxicity": 0.0013601661194115877, "severe_toxicity": 0.0001169632887467742, "obscene": 0.00018989984528161585, "threat": 0.0001329302176600322, "insult": 0.00018336044740863144, "identity_attack": 0.00018879494746215641}}
